### ISSUE TITLE
Possible way to avoid `less` hack?

### ISSUE THREAD

**Issue by wanderingstan** [error-central/diffenv#24]
This ariticle shows how to run `less` from within Python: 
https://chase-seibert.github.io/blog/2012/10/31/python-fork-exec-vim-raw-input.html

Headline *Using less as a pager*

Could that get us away from the `diffenv-nopaging` hack?

(I'm also curious about the first section, of popping open an editor!)

**Comment by werg** [comment]
Should be implemented with #26
