### ISSUE TITLE
Hide sensitive env vars

### ISSUE THREAD

**Issue by wanderingstan** [error-central/diffenv#8]
@werg  We don't want people accidentally sharing keys and passwords. 

By default seems it would be good to hide or hash env vars containing `KEY` or `SECRET`. 

Maybe output a message to stderr that this has been done, and explain that there's a flag to turn off this protection. Maybe we should also have a flag to hash _all_ env vars? 

Keys that I had:
- INFURA_KEY
- GOOGLE_CLIENT_SECRET
- PRISMA_MANAGEMENT_API_SECRET
- SENDGRID_API_KEY

**Comment by werg** [comment]
Yes! That would be a fantastic idea

**Comment by wanderingstan** [comment]
Cool. And sorry..just realized my github notifications were going to my old work email. Now I'll get notified!
